apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: das-advent-pvc
  labels:
    app: das-advent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
