apiVersion: v1
kind: Service
metadata:
  name: das-advent
  labels:
    app: das-advent
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: das-advent
